# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeee53bdb0cad2d90e7c731119643299fb6853d66ff41b8dca69072ddc5c6ab8c51f2bb55e5b641545a3aefff4ca189fc2643139392abae53a31be413fc4bdb9

test:
  secret_key_base: 6f72a2af9e0a9e5ac4a081d80e9027c982f7f037eb43141b1be64228991fc3175c9311187da742c8df925b4cb692009369608de83187944555b0ad6a9c4f22d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
